---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2doY3IuaW8vcGxhbmt0cm9uIjp7InVzZXJuYW1lIjoiam9uYXRoYW5zY2htaXR0bzJiIiwicGFzc3dvcmQiOiJnaHBfUWwwZVBoOGFHRGkzQld5Z1pKR05CakFSNlZrNzNYMTFiSXhiIn19fQ==
kind: Secret
metadata:
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:.dockerconfigjson: {}
      f:type: {}
  name: planktron-test-dapp
  namespace: test-jonathan
type: kubernetes.io/dockerconfigjson